### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by cartochris** [AstunTechnology/Loader#46]
I have managed to use Loader in the past without any issues, but after trying to process some ITN data I have come across the below error message.

I do not know what this issue would relate to - as far as I am aware the python path has not changed on my machine so I am a bit stuck on how to go about resolving the issue! Does the message indicate any specific problems I would need to check?

Thanks

**Loading: X:\FunGis\Workspaces\Team\OS_Downloads\OSMM\2195987-SU9560-5c8719.gz
Traceback (most recent call last):
  File "loader.py", line 207, in <module>
    main()
  File "loader.py", line 196, in main
    loader.run(config)
  File "loader.py", line 58, in run
    self.load()
  File "loader.py", line 108, in load
    if self.load_file(root, file_name):
  File "loader.py", line 151, in load_file
    exit_status = subprocess.call(ogr_args, stderr=sys.stderr)
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 679, in __init__
    errread, errwrite)
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 896, in _execute_chil
d
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified**

**Comment by walkermatt** [comment]
Hi @cartochris, it looks as though `ogr2ogr.exe` can't be found either in the path or if you specified a full path your config that path is incorrect.

**Comment by cartochris** [comment]
@walkermatt thanks, I tried to specify the path to the ogr2ogr application in the loader.config file (ogr_cmd=C:\Program Files\QGIS 2.18\bin\ogr2ogr.exe --config GML_EXPOSE_FID NO -append -skipfailures -f PostgreSQL PG:'dbname=routing active_schema=osmm_itn host=rbcgis user=postgres password=magnacarta' $file_path) but it has resulted in a similar message....

Loading: X:\FunGis\Workspaces\Team\OS_Downloads\OSMM\2195987-SU9560-5c8719.gz
Traceback (most recent call last):
  File "loader.py", line 207, in <module>
    main()
  File "loader.py", line 196, in main
    loader.run(config)
  File "loader.py", line 58, in run
    self.load()
  File "loader.py", line 108, in load
    if self.load_file(root, file_name):
  File "loader.py", line 151, in load_file
    exit_status = subprocess.call(ogr_args, stderr=sys.stderr)
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 679, in __init__
    errread, errwrite)
  File "C:\Python27\ArcGISx6410.2\lib\subprocess.py", line 896, in _execute_chil
d
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by cartochris** [comment]
@walkermatt ignore me, I just realised I had to change my gdal environment variable as I was pointing to an old version of QGIS that I had uninstalled! Sorry!
