### ISSUE TITLE
Loading OS Highways fails on ŷ character

### ISSUE THREAD

**Issue by ianturton** [AstunTechnology/Loader#67]
prep4gml throws an exception inside an exception:

ERROR 1: XML parsing of GML file failed : not well-formed (invalid token) at lin
e 2017529, column 35
Processing: C:\Users\astun-Ian\Documents\data\data\Highways_Rrami_Street_FULL_03
6.gml.gz
Traceback (most recent call last):
  File "prepgml4ogr.py", line 91, in output
    sys.stdout.write(str.encode('utf_8', 'xmlcharrefreplace').decode('utf_8'))
  File "C:\OSGeo4W64\apps\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0176' in position
822: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prepgml4ogr.py", line 162, in <module>
    main()
  File "prepgml4ogr.py", line 145, in main
    parser.parse(file)
  File "C:\OSGeo4W64\apps\Python37\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\OSGeo4W64\apps\Python37\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\OSGeo4W64\apps\Python37\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "c:\_work\4\s\modules\pyexpat.c", line 466, in EndElement
  File "C:\OSGeo4W64\apps\Python37\lib\xml\sax\expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "prepgml4ogr.py", line 85, in endElement
    output(self.preparer.prepare_feature(''.join(self.buffer)))
  File "prepgml4ogr.py", line 93, in output
    sys.stdout.write(str.encode('utf_8', 'xmlcharrefreplace'))
TypeError: write() argument must be str, not bytes

My suspicion is that none of this is needed now that Python3 handles UTF-8 directly (though what windows will do with it is another question).

**Comment by walkermatt** [comment]
@ianturton have you tried the suggestion in this issue: https://github.com/AstunTechnology/Loader/issues/66#issuecomment-501258735 ?

**Comment by ianturton** [comment]
I haven't - I just commented out the encode/decode and replaced with 

     sys.stdout.write(str)

which seems to be working

**Comment by walkermatt** [comment]
Removing Python 2 support would sure simplify things but it's probably a little too soon?

**Comment by ianturton** [comment]
That seems to fix the issue
