### ISSUE TITLE
Errors when loading Mastermap Topography into SQL Server

### ISSUE THREAD

**Issue by RobShaw77** [AstunTechnology/Loader#70]
I'm trying to use Astun Loader to import Mastermap Topography into SQL Server. When I run it I get the following output:

```
C:\OS Mastermap Topo\AstunLoader\python\loader.py:138: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exit_status is not 0:
C:\OS Mastermap Topo\AstunLoader\python\loader.py:156: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exit_status is not 0:
C:\OS Mastermap Topo\AstunLoader\python\loader.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exit_status is not 0:
C:\OS Mastermap Topo\AstunLoader\python\loader.py:186: DeprecationWarning: 'U' mode is deprecated
  with open(config_file, 'rU') as f:
Processing: E:/MMTopo raw/tmp\5823014-NT6000.gz
Loading: E:/MMTopo raw/tmp\5823014-NT6000.gz
Traceback (most recent call last):
  File "C:\OS Mastermap Topo\AstunLoader\python\loader.py", line 211, in <module>
    main()
  File "C:\OS Mastermap Topo\AstunLoader\python\loader.py", line 200, in main
    loader.run(config)
  File "C:\OS Mastermap Topo\AstunLoader\python\loader.py", line 60, in run
    self.load()
  File "C:\OS Mastermap Topo\AstunLoader\python\loader.py", line 112, in load
    if self.load_file(root, file_name):
  File "C:\OS Mastermap Topo\AstunLoader\python\loader.py", line 155, in load_file
    exit_status = subprocess.call(ogr_args, stderr=sys.stderr)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Could anyone advise what may be wrong please?

Thanks
Rob

**Comment by walkermatt** [comment]
Hi Rob, The warnings can be ignored, we should update Loader to avoid them in future but they shouldn't affect the operation.

I've struggled to find a reasonable explanation for the actual error you're seeing. A couple of things to try one at a time:

* Make sure the current working directory is the `python` folder of your copy of Loader before running Loader (`cd /d "C:\OS Mastermap Topo\AstunLoader\python\"`)
* Try removing spaces from your `src_dir`, `out_dir` and `tmp_dir` paths (both the folder names and in your `loader.config`
* It's possibly an issue with Python installed from the Windows App Store, see the last comment on [this SO question](https://stackoverflow.com/questions/71842400/script-with-subprocess-not-working-on-a-other-windows-pc)

**Comment by RobShaw77** [comment]
Matt

Thanks for your help. I removed the spaces from the directory names and reinstall python directly. I also modified line 155 in loader.py to add `shell=True` to `subprocess.call(ogr_args, stderr=sys.stderr)`,

It now loads some of the data successfully into SQL Server but it is blanking several of the fields due to the error:

```
 Warning 1: The output driver does not natively support StringList type for field theme. Misconversion can happen. -mapFieldType can be used to control field type conversion.
Warning 6: Can't create field theme with type StringList on MSSQL layers.  Creating as varchar.
ERROR 1: INSERT command for new feature failed. [22001][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated.(8152), [01000][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.(3621)
```

I've tried adding `-fieldTypeToString StringList` to the ogr command but I still get the latter of those errors.

Any further help much appreciated.

Rob

**Comment by walkermatt** [comment]
@RobShaw77 fantastic 😋
